version: "3"

services:
  database:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  webdb:
    image: webdb/app
    restart: always
    volumes:
      - "$HOME/.webdb:/usr/src/app/static/version"
    ports:
      - "127.0.0.1:22072:22072"
    depends_on:
      - database
volumes:
  database_data:
